services:
  - type: web
    name: psu-certificate-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/src/data/database.sqlite
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
    disk:
      name: psu-certificate-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1